name: Build and Publish Docker Image to GHCR
on:
  push:
    paths:
      - '.github/workflows/test_docker.yml'
      - 'src/Common/Version.props'
      - '**/*.csproj'
      - '**/*Dockerfile.*'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/test_docker.yml'
      - '**/*Dockerfile.*'
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    
    - name: Install prerequisites and download drivers
      shell: bash
      run: ./build.sh --download-driver
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=noble-latest,enable={{is_default_branch}}
    
    - name: Build Docker image
      run: |
        bash utils/docker/build.sh --amd64 noble playwright-dotnet:localbuild-noble
    
    - name: Tag and push Docker image
      run: |
        docker tag playwright-dotnet:localbuild-noble ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:noble-latest
        docker tag playwright-dotnet:localbuild-noble ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:noble-latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
